const VALID_KEYS = [
    'xk47n2',
    'mb9p3r',
    'zt5h8w',
    'qy2v4m',
    'ln6j9c',
    'wd3f5k',
    'as8u4p',
    'hg7b2n',
    'jr4t6m',
    'vx9c3l',
    'pk5w8d',
    'ym2q7h',
    'bf6n9s',
    'tc4g5r',
    'kl8m3w',
    'dx7p4v',
    'nq2h6t',
    'uw5b9j',
    'em3f8k',
    'ry6l4s',
    'gz9v2c',
    'ax4m7h',
    'wt8k2p',
    'ql6d3n',
    'bj9f5r',
    'hs2w7m',
    'cv5t8l',
    'py4g6k',
    'mx3b8w',
    'fd7n2v',
    'jtv',
    'test',
    'dev-test',
    

    'Palu4',
    'Venixi_ua',
    'Smile_dimasikTV',
    'JOKER_UAG'
];

module.exports = VALID_KEYS;
